### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizergit** [prcutler/nflpool#204]
Greetings, @prcutler 

I am a designer in development and an open source enthusiast who would love to contribute to your project by designing a logo for it. I found your project exploring GitHub and found it interesting. About the process, we would be working together to create the logo that fits best with your project. The process is, of course, totally free and you can quit whenever you want. In case you agree, it would be useful if you had any ideas (shapes, colours, etc) to have something to start with.

Best regards!

**Comment by prcutler** [comment]
Hi Michael!

Thanks for reaching out!  Yes, I'd definitely be interested in a logo for NFLPool.  I am not very good at design or user experience, be warned.  :)  

You can see NFLPool in production at https://nflpool.xyz - I'd love to replace the "NFLPool" text in the upper left hand corner with a logo.  Something that probably has a transparent image that would work well under the black title bar.  (I can make the bar bigger to allow a logo, too)

As far as ideas - maybe something that uses an American football?  Probably don't want anything related to the NFL's shield logo (I'm already afraid that someday I'll have to change the name of the app and remove "NFL" as it's their copyrighted trademark).  I'm open to ideas, I'm terrible at brainstorming this kind of stuff and would be happy to continue the conversation with any ideas you have.

Thanks again and look forward to hearing from you!

**Comment by michaelizergit** [comment]
Hello, I'm so sorry for disappearing I was finishing a semester. I want to resume the work as soon as possible just passing by to ask if you are still interested.

**Comment by prcutler** [comment]
No problem!  Absolutely still interested.  I almost pinged you yesterday, glad to know your'e still interested in helping out.  Thanks!

**Comment by prcutler** [comment]
Hi Michael,

Thanks so for much for working on this!  

One question - what would it look like it if you took the water effect away and just used the font?  I ask because while the app is "NFLPool" it's more of a betting pool than water related and I don't want to cause confusion for new players.   What are your thoughts?

Thanks again - I really appreciate you taking time to work on this.

Paul

**Comment by michaelizergit** [comment]
Hello, here you have some sketches, I want to hear your opinion about them.
![logos 2](https://user-images.githubusercontent.com/43072298/50497826-be9a0f00-0a11-11e9-8d30-382997665b53.png)

**Comment by prcutler** [comment]
Hi,

Sorry for the delay getting back to you, been busy over the holidays.

Thanks for doing these!  I like the third one down the most, but it's pretty close.  I also like #2.

Paul

**Comment by michaelizergit** [comment]
Merry Christmas hahaha. I can use the coins like Os on #3. Apart from that, what would you like me to add/modify?

**Comment by prcutler** [comment]
Actually, I like the coins not being the O's.  I can't think of anything else to modify, looks good to me.

**Comment by michaelizergit** [comment]
Great! do you want me to upload the files through a pull request? I will add the svg and pdf version for you to have full control of your logo.

**Comment by michaelizergit** [comment]
Done! ([#253](https://github.com/prcutler/nflpool/pull/253)), it was a real pleasure for me. Thanks for offering to give credits. You could add this e-mail: the.skull.ojbs@gmail.com and I'm from Venezuela so if you also want to add my phone number, it is +58 414-0462303. Have a great day, sir.

**Comment by michaelizergit** [comment]
You are very welcome! have a nice trip by the way :))
