### ISSUE TITLE
Getting error while trying to run the project

### ISSUE THREAD

**Issue by efebuyuk** [prcutler/nflpool#342]
I am getting the below error while running it. Could you figure out why? Thank you.

pkg_resources.DistributionNotFound: The 'nflpool' distribution was not found and is required by the application

**Comment by prcutler** [comment]
What steps did you do to install the project?

Off the top of my head:

1. git clone the project

2. Install the requirements via pip (in a virtual environment!):  `pip install -e requirements.txt`

3. Run setup.py:  `python3 setup.py develop`

That last step should fix the error as it installs nflpool as a module

Then you can start the Pyramid server using pserve as normal.  

Let me know if you have any more questions or issues.

--Paul

**Comment by prcutler** [comment]
Any luck?  Did it work?

**Comment by efebuyuk** [comment]
After I did the 3rd step (which fixed the initial problem) then I got this following error while trying to run `pserve development.ini`;

`    import nflpool.data.secret as secret
ModuleNotFoundError: No module named 'nflpool.data.secret'`

**Comment by prcutler** [comment]
Did you take a look at the docs(https://nflpool.readthedocs.io/en/latest/admin-docs/install.html) and create the secret.py file in the data directory?

If you did do that, let me know, and I'll try and re-create the issue.  Sorry for the problems, would like to get them fixed for anyone else who might ever want to use it.  Really appreciate you opening the issue.

--Paul

**Comment by efebuyuk** [comment]
I found the file 'secret.py' but there is another issue that we need to fill in that file. I need an account information and API key.. Is there any test account that we can use? or should I just create one by myself?

**Comment by prcutler** [comment]
You have to have an account with MySportsFeeds - it's by far the least expensive option anywhere to get sports statistics - their competitors charge hundreds to thousands of dollars per month for similar services. 

I believe if you create an account at https://www.mysportsfeeds.com/register access to past seasons data is free (which would work for testing), but if you are going to run this in real time, you'll need to contribute $1 per month for NFLPool to work.

**Comment by prcutler** [comment]
Closing this as running `python setup.py develop` worked.  If you run into any other issues, please open a new issue, happy to help.
